### PR TITLE
Allow additional arguments to be passed through serialize()

### PR DESCRIPTION
**Pull request by akuker**

### CODE REVIEW

**Comment by da4089** [comment]
Hi @akuker -- thanks for the contribution!

Do you have a use for this ability to pass extra args in mind?

**Comment by akuker** [comment]
Hi @da4089 - For my use case, I want to be able to filter which properties/fields are included in the serialized output. For example, I might want to serialize the data with only the full name and phone number. 

I can't share too much about my specific use case, but in general, the client to my phone book server can specify which fields it wants to receive, and which it doesn't.  For this example, I'm creating my own behavior class and passing in an object that enables/disables the fields.

Here's an example....

```
class CustomVcard(VCardBehavior):

    @classmethod
    def serialize(cls, obj, buf, lineLength, *args, validate=True, 
        property_mask: PropertyMask = PropertyMask(0),
        **kwargs,
    ):
        # Do stuff.... filter based upon PropertyMask
```

By adding the args and kwargs to the base serialize() method, the base VCardBehavior will just pass through any unknown args to the derived class. If there aren't extra args specified, this change will have no effect.

Hopefully that helps!

**Comment by da4089** [comment]
Merged, thanks!

**Comment by akuker** [comment]
Thank you @da4089 !

**Pull request merged**
